<?xml version="1.0" encoding="windows-1251"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:import-schema schema-location="ModelResults.xsd"/>
	<xsl:template match="/">
		<html>
			<head>
				<title>Модель тенденций</title>
			</head>
			<body>
                График заданного верменного ряда<br/>
                <img src="Временной ряд.png" alt="Временной ряд"></img>
                <br/>
				<xsl:for-each select="$XML">
				Таблица внутренних и внешних ошибок<br/>
					<table border="1">
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>MSE</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>RMSE</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>MAPE</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>R2</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="ReportOfCrispResultRowFuzzyResultRow">
								<xsl:for-each select="Errors">
									<xsl:for-each select="ErrorRow">
										<tr>
											<td>
												<xsl:for-each select="MSE">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="RMSE">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="MAPE">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="R2">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
										</tr>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<table border="1">
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>FPE</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>FCE</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>TTend FPE</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>TTend FCE</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>RTend FPE</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>RTend FCE</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="ReportOfCrispResultRowFuzzyResultRow">
								<xsl:for-each select="FErrors">
									<xsl:for-each select="FuzzyErrorRow">
										<tr>
											<td>
												<xsl:for-each select="FPE">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="FCE">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="TTendFPE">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="TTendFCE">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="RTendFPE">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="RTendFCE">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
										</tr>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<br/>
					Информация о модели:
					<xsl:for-each select="ReportOfCrispResultRowFuzzyResultRow">
					<xsl:for-each select="ModelInfo">
						<xsl:apply-templates/>
					</xsl:for-each>
					<br/>
					Информация о шкале:
					<xsl:for-each select="ACLInfo">
						<xsl:apply-templates/>
					</xsl:for-each>
                    </xsl:for-each>					
				</xsl:for-each>
					<br/>
					<br/>
                График принадлежности точек временного ряда соответсвущим нечетким множествам<br/>
                <img src="Принадлежность.png" alt="Принадлежность"></img>
                <br/>
                График центров нечетких множеств нечеткого временного ряда<br/>
                <img src="Ряд центров НМ.png" alt="Ряд центров НМ"></img>
                <br/>
                График ряда разностей<br/>
                <img src="Ряд разностей.png" alt="Ряд разностей"></img>
                <br/>
                График ряда разностей - модель<br/>
                <img src="Ряд разностей Модель.png" alt="Ряд разностей Модель"></img>
                <br/>
                График ошибок модели<br/>
                <img src="Ряд ошибок.png" alt="Ряд ошибок"></img>
                <br/>
                График относительных ошибок модели<br/>
                <img src="Ряд относительных ошибок.png" alt="Ряд относительных ошибок"></img>
                <br/>
				<xsl:for-each select="$XML">
					 Результаты применения модели
					<table border="1">
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>Время</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Ряд</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Модель</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Ошибка</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Отн. Ошибка</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Разность</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Модель Разность</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="ReportOfCrispResultRowFuzzyResultRow">
								<xsl:for-each select="ResultCrisp">
								<xsl:for-each select="CrispResultRow">
									<tr>
										<td>
											<xsl:for-each select="Time">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="Series">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="Model">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="Error">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="RError">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="Diff">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="ModelDiff">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
									</tr>
								</xsl:for-each>
							</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<br/>
					<table border="1">
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>Время</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Ряд</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>ФП</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>НМ</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Модель НМ</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Ошибка</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>TTend</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Модель TTend</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Ошибка</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>RTend</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Модель RTend</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Ошибка</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="ReportOfCrispResultRowFuzzyResultRow">
								<xsl:for-each select="ResultFuzzy">
								<xsl:for-each select="FuzzyResultRow">
									<tr>
										<td>
											<xsl:for-each select="Time">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="Series">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="MF">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="FT">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="ModelFT">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="FTError">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="TTend">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="ModelTTend">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="TError">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="RTend">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="ModelRTend">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="RError">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
									</tr>
								</xsl:for-each>
							</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<br/>
					Таблица правил для Разности<br/>
					<table border="1">
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>Number</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Rule</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Count</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="ReportOfCrispResultRowFuzzyResultRow">
								<xsl:for-each select="RuleRTend">
									<xsl:for-each select="RuleRow">
										<tr>
											<td>
												<xsl:for-each select="Number">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="Rule">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="Count">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
										</tr>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					Таблица правил для Разности<br/>
					<table border="1">
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>Number</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Rule</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>MF</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="ReportOfCrispResultRowFuzzyResultRow">
								<xsl:for-each select="RuleMFRTend">
									<xsl:for-each select="RuleMFRow">
										<tr>
											<td>
												<xsl:for-each select="Number">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="Rule">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td>
												<xsl:for-each select="MF">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
										</tr>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
